CommunityToolkit/Aspire

.devcontainer/post-create.sh
.github/workflows/dotnet-ci.yml
.github/workflows/dotnet-main.yml
.github/workflows/dotnet-release.yml

**Closes #99**
Replace 
`dotnet workload install aspire`
by
`dotnet workload update && dotnet workload install aspire`
in the workflows to prevent Workflow failure when .NET Aspire manifest is not up-to-date

Updating workload manifest before install Aspire in Workflows

---

.github/workflows/dotnet-ci.yml
.github/workflows/dotnet-main.yml
CONTRIBUTING.md
README.md
docs/faq.md
docs/versioning.md

Fixes #117 
Will remove github packages later once ado is sorted

Adding Azure artifacts nuget feed to publishing

---

Directory.Build.props
docs/create-integration.md
src/Aspire.CommunityToolkit.Hosting.Azure.StaticWebApps/Aspire.CommunityToolkit.Hosting.Azure.StaticWebApps.csproj
src/Aspire.CommunityToolkit.Hosting.Golang/Aspire.CommunityToolkit.Hosting.Golang.csproj
src/Aspire.CommunityToolkit.Hosting.Java/Aspire.CommunityToolkit.Hosting.Java.csproj
src/Aspire.CommunityToolkit.Hosting.NodeJS.Extensions/Aspire.CommunityToolkit.Hosting.NodeJS.Extensions.csproj
src/Aspire.CommunityToolkit.OllamaSharp/Aspire.CommunityToolkit.OllamaSharp.csproj
src/Directory.Build.props

- **Forgot to add the readme to the nuspec**
- **Improving local packaging version suffix**
- **Improving the packages with descriptions**

nuget package fixes

---

src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaResourceLifecycleHook.cs

**Closes #118**
Making the model name check happen on the exact model name rather than the start of the model name. This is to prevent false positives when the model name is a substring of another model name.
A unit test would have been good but I can't figure out how to do it without a huge overhaul to support mocking (which isn't ideal for a simple change).

Better handling of ollama model discovery

---

.github/workflows/dotnet-ci.yml

ignore artifact publishing when its depndabot

---

README.md

Add Meilisearch badges to README.md

Add Meilisearch badges to README.md

---

src/CommunityToolkit.Aspire.Meilisearch/AspireMeilisearchExtensions.cs
src/CommunityToolkit.Aspire.Meilisearch/README.md

This pull request includes minor changes to the `CommunityToolkit.Aspire.Meilisearch` project, focusing on documentation and configuration updates.
Documentation updates:
* [`src/CommunityToolkit.Aspire.Meilisearch/AspireMeilisearchExtensions.cs`](diffhunk://#diff-8f147896325337505e9b1335db2c5e61457deca5070ef1264509e958b6f8b6c7L39-R39): Updated the summary comment to correctly refer to `MeilisearchClient` instead of `Meilisearch`.
Configuration updates:
* [`src/CommunityToolkit.Aspire.Meilisearch/README.md`](diffhunk://#diff-90e395908f691f5b4d18b2d9c22b4c696c88e55d693fab796b4cd0003c049e66L58-R58): Added a comma after the `Endpoint` value in the JSON configuration example.

Fix Meilisearch doc issues

---

.editorconfig
Directory.Build.props
src/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps/SwaApiEndpointAnnotation.cs
src/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps/SwaAppEndpointAnnotation.cs
src/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps/SwaAppHostingExtension.cs
src/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps/SwaResource.cs
src/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps/SwaResourceOptions.cs
src/CommunityToolkit.Aspire.Hosting.Golang/GolangAppExecutableResource.cs
src/CommunityToolkit.Aspire.Hosting.NodeJS.Extensions/NodeJSHostingExtensions.cs
src/CommunityToolkit.Aspire.Hosting.NodeJS.Extensions/NodePackageInstaller.cs
src/CommunityToolkit.Aspire.Hosting.NodeJS.Extensions/NpmPackageInstallerLifecycleHook.cs
src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaResource.cs
src/CommunityToolkit.Aspire.OllamaSharp/AspireOllamaSharpExtensions.cs
src/Directory.Build.props

- **Editor config + compiler to enforce XML docs**
- **Adding all the missing docs**
Fixes #144

Enforcing XML docs

---

.github/workflows/dotnet-ci.yml
.github/workflows/dotnet-main.yml
.github/workflows/dotnet-release.yml

Caching global npm packages

---

Directory.Build.props
Directory.Packages.props

Preparing the 8.3.0 release with a few package updates

Release v8.3.0

---

.github/workflows/code-coverage.yml

We don't need everything in there so let's get rid of stuff that is just causing
noise. The focus should be assemblies under src, not examples.
Contributes to #168

Code Coverage improvements

---

src/CommunityToolkit.Aspire.OllamaSharp/AspireOllamaSharpExtensions.cs
tests/CommunityToolkit.Aspire.Hosting.Ollama.Tests/CommunityToolkit.Aspire.Hosting.Ollama.Tests.csproj
tests/CommunityToolkit.Aspire.Hosting.Ollama.Tests/OllamaFunctionalTests.cs

Add Ollama functional tests

---

CODEOWNERS

Adding @ErikEJ @jmezach as codeowners for the database projects integration

SQL Database Projects codeowner

---

README.md

Add Rust and SQL Databases project shields to readme

---

examples/sql-database-projects/SdkProject/SdkProject.csproj
src/CommunityToolkit.Aspire.Hosting.Meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.csproj
src/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects.csproj
src/CommunityToolkit.Aspire.Meilisearch/CommunityToolkit.Aspire.Meilisearch.csproj

Silent vulnerable package warning

---

Directory.Build.props
Directory.Packages.props
src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaResourceBuilderExtensions.Model.cs
src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaResourceBuilderExtensions.cs
tests/CommunityToolkit.Aspire.Hosting.Ollama.Tests/AddOllamaTests.cs

Updating to Aspire 9.0.0 GA

---

examples/sql-database-projects/SdkProject/SdkProject.csproj

Update to 3.0.0 Build SDK in SQL Database Projects sample

---

src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaContainerImageTags.cs

Bumping Ollama container image

---

src/CommunityToolkit.Aspire.Hosting.Meilisearch/MeilisearchContainerImageTags.cs

Update Meilisearch tag to v1.11

---

README.md

Add bun shields to readme

---

examples/java/CommunityToolkit.Aspire.Hosting.Java.Spring.Maven/src/main/java/org/aliencube/aspire/contribs/spring_maven/controllers/WeatherController.java
src/CommunityToolkit.Aspire.Hosting.Golang/GolangAppHostingExtension.cs
src/CommunityToolkit.Aspire.Hosting.Python.Extensions/UvicornAppHostingExtension.cs
src/CommunityToolkit.Aspire.Hosting.Python.Extensions/UvicornAppResource.cs
src/Directory.Build.props
src/Directory.Build.targets

Doc errors fail builds

---

src/CommunityToolkit.Aspire.Hosting.Python.Extensions/UvicornAppHostingExtension.cs
tests/CommunityToolkit.Aspire.Hosting.Meilisearch/MeilisearchPublicApiTests.cs
tests/CommunityToolkit.Aspire.Hosting.Rust.Tests/RustAppPublicApiTests.cs
tests/CommunityToolkit.Aspire.Testing/ConformanceTests.cs

**Closes #254 **
Fixes a few minor warnings during compilation.

#254 small fixes for compilation warnings

---

src/CommunityToolkit.Aspire.Hosting.Meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.csproj
src/CommunityToolkit.Aspire.Meilisearch/CommunityToolkit.Aspire.Meilisearch.csproj

Remove NoWarn from Meilisearch integrations

---

examples/ollama/CommunityToolkit.Aspire.Hosting.Ollama.Web/Program.cs

Registering correct AI services in Ollama example

---

src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaContainerImageTags.cs

#293 bump Ollama tags

---

src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaResourceBuilderExtensions.cs
tests/CommunityToolkit.Aspire.Hosting.Ollama.Tests/AddOllamaTests.cs

Fix Ollama GPU support

---

.github/copilot-instructions.md

Feature info: https://docs.github.com/en/copilot/customizing-copilot/adding-custom-instructions-for-github-copilot

Adding copilot-instructions

---

README.md

Add ActiveMQ and Eventstore shield badges to Readme

---

.devcontainer/devcontainer.json
.devcontainer/post-create.sh
.vscode/tasks.json
CONTRIBUTING.md
docs/create-integration.md
docs/setup.md

- **Improving the contributor guide**
- **Adding package managers to manual steps**

contributor docs improvements

---

CODEOWNERS

codeowners update

---

src/CommunityToolkit.Aspire.Hosting.ActiveMQ/ActiveMQContainerImageTags.cs
tests/CommunityToolkit.Aspire.Hosting.ActiveMQ.Tests/ContainerResourceCreationTests.cs

#361 bump apache/activemq-classic to 6.1.4

---

src/CommunityToolkit.Aspire.Hosting.Meilisearch/MeilisearchContainerImageTags.cs

Update Meilisearch container image tag to v1.12

---

.github/workflows/dotnet-ci.yml

Trying to hard-code the Deno version to last known working (#391)

---

tests/CommunityToolkit.Aspire.Hosting.Azure.DataApiBuilder.Tests/AppHostTests.cs

**Does not close #405 **
Removes FluentAssertions from DataApiBuilder

#405 removed FA from DataApiBuilder

---

tests/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps.Tests/ResourceCreationTests.cs
tests/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps.Tests/SwaHostingComponentTests.cs

**Contributes to #405 **
Remove FluentAssertions from StaticWebApps and removed unused usings

#405 Removed FA from StaticWebApps

---

.github/workflows/remove-stale-label.yml
.github/workflows/stale-issues.yml

- Changing how stale issues are detected
- Adding new workflow to allow people to manually extend the stale period

Stale issue workflow improvements

---

docs/create-integration.md

Remove FA usage from docs

---

Directory.Packages.props
src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaContainerImageTags.cs

- **Updating ollama image tag**
- **Bumping OllamaSharp version**
Replaces #419

ollama update

---

.github/actions/setup-runtimes-caching/action.yml
.github/workflows/dotnet-ci.yml
.github/workflows/dotnet-main.yml
.github/workflows/dotnet-release.yml

Converting our workflow to use a set of composite actions for the runtime setup and caching. See https://docs.github.com/en/actions/sharing-automations/avoiding-duplication for info on reducing duplication

Improving CI

---

src/CommunityToolkit.Aspire.Hosting.ActiveMQ/README.md

#451 Added examples for ActiveMQ Artemis

---

src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaContainerImageTags.cs

Making Ollama container image stable and bumping OpenWebUI

---

.devcontainer/devcontainer.json

**Closes #487**
Modify the additionalVersions property value of the dotnet feature in the devcontainer.json

Fix the devcontainers dotnet feature version

---

src/CommunityToolkit.Aspire.RavenDB.Client/README.md

Aspire-490 - Fix RavenDB README.md

---

.vscode/settings.json
Directory.Build.props
Directory.Packages.props
examples/ollama/CommunityToolkit.Aspire.Hosting.Ollama.Web/Components/Pages/Home.razor
tests/CommunityToolkit.Aspire.OllamaSharp.Tests/OllamaApiClientTests.cs
tests/CommunityToolkit.Aspire.OllamaSharp.Tests/OllamaSharpIChatClientTests.cs
tests/CommunityToolkit.Aspire.OllamaSharp.Tests/OllamaSharpIEmbeddingGeneratorTests.cs

Updating to latest MEAI

---

src/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects/SqlProjectPublishService.cs
src/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects/SqlProjectResource.cs

fixes #506
- Use correct assembly reference to determine configuration
- Add more logging to console logs
**Closes #506**
/cc @jmezach @aaronpowell

Fix showstopper bug in SQL Projects hosting extension

---

src/CommunityToolkit.Aspire.Hosting.Azure.Dapr/AzureDaprPublishingHelper.cs
src/CommunityToolkit.Aspire.Hosting.Dapr/DefaultDaprPublishingHelper.cs
src/Shared/Dapr/Core/DaprDistributedApplicationLifecycleHook.cs
src/Shared/Dapr/Core/IDaprPublishingHelper.cs

**Closes #542**
Check all resources for containerappcustomisation annotation
- [`x] Created a feature/dev branch in your fork (vs. submitting directly from a commit on main)

Fixes to make sure all dapr sidecars are configured correctly for azure

---

src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaResourceBuilderExtensions.OpenWebUI.cs
tests/CommunityToolkit.Aspire.Hosting.Ollama.Tests/AddOllamaTests.cs

Included test coverage
Fixes #505

Adding a WithHostPort method for setting the port on OpenWebUI

---

Directory.Packages.props
src/CommunityToolkit.Aspire.Hosting.Azure.Dapr.Redis/AzureRedisCacheDaprHostingExtensions.cs
src/CommunityToolkit.Aspire.Hosting.Azure.Dapr.Redis/CommunityToolkit.Aspire.Hosting.Azure.Dapr.Redis.csproj
tests/CommunityToolkit.Aspire.Hosting.Azure.Dapr.Redis.Tests/ResourceCreationTests.cs

**Closes #435 & #515**
Recreating https://github.com/CommunityToolkit/Aspire/pull/517

Dapr redis ext fixes

---

.github/workflows/dotnet-ci.yml
.github/workflows/dotnet-main.yml
.github/workflows/dotnet-release.yml
.github/workflows/tests.yaml
src/Shared/DaprAzureExtensions/AzureDaprHostingExtensions.cs
tests/CommunityToolkit.Aspire.Hosting.Azure.Dapr.Redis.Tests/ResourceCreationTests.cs
tests/CommunityToolkit.Aspire.Hosting.Azure.Dapr.Tests/ResourceCreationTests.cs

Make dapr name to lower

---

.github/actions/setup-runtimes-caching/action.yml
.github/workflows/dotnet-ci.yml
.github/workflows/dotnet-main.yml
.github/workflows/dotnet-release.yml
.github/workflows/tests.yaml

Adding login step for docker

---

src/CommunityToolkit.Aspire.Hosting.Sqlite/SqliteResourceBuilderExtensions.cs
tests/CommunityToolkit.Aspire.Hosting.Sqlite.Tests/AddSqliteTests.cs

Adding parent relationship for sqlite-web

---

.github/actions/setup-runtimes-caching/action.yml

builds from forks won't have access to secrets, meaning that they will not have the username/password, and the build will fail

Only doing docker-login if it's from a local branch

---

examples/ollama/CommunityToolkit.Aspire.Hosting.Ollama.AppHost/Program.cs
src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaContainerImageTags.cs
src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaResourceBuilderExtensions.OpenWebUI.cs
src/CommunityToolkit.Aspire.Hosting.Ollama/OpenWebUIResource.cs
tests/CommunityToolkit.Aspire.Hosting.Ollama.Tests/AddOllamaTests.cs

Supporting multiple Ollama hosts in Open WebUI

---

src/CommunityToolkit.Aspire.Hosting.Azure.Dapr/README.md
src/CommunityToolkit.Aspire.Hosting.Dapr/README.md
src/Shared/Dapr/Core/DaprDistributedApplicationLifecycleHook.cs
src/Shared/Dapr/Core/DaprSidecarOptions.cs

Bringing Dapr changes into main

dapr fixes

---

src/CommunityToolkit.Aspire.Hosting.Bun/BunPackageInstallerLifecycleHook.cs

Handling package.json workspaces in Bun

---

Directory.Build.props

Should be merge after 9.4 release.

Update packages baseline

---

Directory.Build.props

Update Microsoft.Extensions.AI version to 9.4.3-preview.1.25230.7

---

src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaContainerImageTags.cs

Update ollama tag

---

Directory.Build.props

Update `Microsoft.Extensions.AI` to 9.4.4-preview.1.25259.16

---

Directory.Build.props

**Closes # do we really need an issue to bump a version? :-) **

Update to stable Microsoft.Extensions.AI

---

Directory.Build.props
src/CommunityToolkit.Aspire.OllamaSharp/CommunityToolkit.Aspire.OllamaSharp.csproj
src/Shared/Dapr/Core/IDistributedApplicationBuilderExtensions.shared.cs
src/Shared/Dapr/Core/IDistributedApplicationComponentBuilderExtensions.cs
tests/CommunityToolkit.Aspire.Hosting.Dapr.Tests/WithDaprSidecarTests.cs
tests/dapr-shared/AddDaprPubSubTests.cs
tests/dapr-shared/AddDaprStateStoreTests.cs

```<IsPreview>true</IsPreview>``` removed from `CommunityToolkit.Aspire.OllamaSharp.csproj` because we use a stable version of MEAI.

Aspire 9.3 upgrade

---

Directory.Build.props

Updating current version to 9.6.1

---

src/CommunityToolkit.Aspire.Hosting.ActiveMQ/ActiveMQArtemisContainerImageSettings.cs
src/CommunityToolkit.Aspire.Hosting.ActiveMQ/ActiveMQBuilderExtensions.cs
src/CommunityToolkit.Aspire.Hosting.ActiveMQ/ActiveMQClassicContainerImageSettings.cs
tests/CommunityToolkit.Aspire.Hosting.ActiveMQ.Tests/ContainerResourceCreationTests.cs

**Closes #762 **
Bumped tags for ActiveMQ Artemis and Classic

#762 bumped ActiveMQ Artimis and Classic tags

---

src/CommunityToolkit.Aspire.Hosting.k6/K6ContainerImageTags.cs

**Closes #834**
Updates the k6 image to the latest version.
None.

[k6] Update k6 container image tag

---

CODEOWNERS

add @oising as owner for powershell bits
n/a
n/a

add @oising as powershell owner

---

Directory.Packages.props

Upgraded the `Microsoft.SqlServer.DacFx` package from version 162.5.57 to 170.1.61. This update may include bug fixes, performance improvements, and new features.
**Closes(https://github.com/CommunityToolkit/Aspire/issues/847)**
No tests exist currently for MS Build SQLServer

Update Microsoft.SqlServer.DacFx to version 170.1.61

---

src/CommunityToolkit.Aspire.Hosting.Azure.DataApiBuilder/DataApiBuilderContainerImageTags.cs

That old version is way-way outdated.

Update hard coded version to "latest"
