CommunityToolkit/Aspire

- src/Aspire.CommunityToolkit.Hosting.Azure.DataApiBuilder/DataApiBuilderHostingExtension.cs
- src/Aspire.CommunityToolkit.Hosting.Azure.StaticWebApps/SwaAppHostingExtension.cs
- src/Aspire.CommunityToolkit.Hosting.Golang/GolangAppHostingExtension.cs
- src/Aspire.CommunityToolkit.Hosting.Java/JavaAppHostingExtension.cs
- src/Aspire.CommunityToolkit.Hosting.NodeJS.Extensions/NodeJSHostingExtensions.cs
- src/Aspire.CommunityToolkit.Hosting.Ollama/OllamaResourceBuilderExtensions.cs
- tests/Aspire.CommunityToolkit.Hosting.Java.Tests/ContainerResourceCreationTests.cs
- tests/Aspire.CommunityToolkit.Hosting.Java.Tests/ExecutableResourceCreationTests.cs
- tests/Aspire.CommunityToolkit.Hosting.Ollama.Tests/AddOllamaTests.cs
Does require a bit of hackery in the tests to tell the analyser to be quiet but that's ok.
Fixes #89
> Adding `ResourceName` attribute to our extension methods

- .github/dependabot.yml
- .github/workflows/stale-issues.yml
- Directory.Build.props
- Directory.Packages.props
With NuGet publishing sorted, it's time to cut a stable release to NuGet.
I've updated our dependencies to use the latest of everything, so Aspire 8.2.1 (current stable), and all additional packages.
To ensure that we can keep up on this stuff I've also added dependabot to do weekly scanning and a stale issue closer (to help clean everything up).
> Preparing 8.2.1 release

- .github/workflows/dotnet-release.yml
- Directory.Build.props
- Directory.Build.targets
- src/Directory.Build.props
Added a failure condition for release builds that if you try to release a version that doesn't match what we'd been building the CI will fail.
Fixes #145
> Changing versioning for builds

- docs/create-integration.md
- src/CommunityToolkit.Aspire.Hosting.Meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.csproj
- src/CommunityToolkit.Aspire.Meilisearch/CommunityToolkit.Aspire.Meilisearch.csproj
- src/CommunityToolkit.Aspire.OllamaSharp/CommunityToolkit.Aspire.OllamaSharp.csproj
Improves discovery in Visual Studio tooling for .NET Aspire by adding the integration type as a tag to the `AdditionalTags` property in the `csproj` file for each integration.
Fixes #146
> Missing NuGet package tags

- tests/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps.Tests/SwaHostingComponentTests.cs
I've extended the timeout to 5 minutes as the logs from the issue seem to suggest that it's just timing out trying to setup the resources that the emulator relies on (install npm packages and what not).
Fixes #157
> Improving SWA test stability

- Directory.Build.props
`ToolkitMinorVersion` should be zero. we should not skip 9.0.* and 9.1.* versions.
@aaronpowell  What happens in the Nuget feed when we merge this PR?
Will the `9.3.0-beta.52` be listed as the last version?
> Update `ToolkitMinorVersion` to 0

- examples/meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.AppHost/Program.cs
- src/CommunityToolkit.Aspire.Hosting.Meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.csproj
- src/CommunityToolkit.Aspire.Hosting.Meilisearch/MeilisearchBuilderExtensions.cs
- tests/CommunityToolkit.Aspire.Hosting.Meilisearch/MeilisearchFunctionalTests.cs
Closes #73 
This pull request introduces several enhancements and bug fixes to the `CommunityToolkit.Aspire.Hosting.Meilisearch` project, including the addition of health checks and the reactivation of previously commented-out code. The most important changes are summarized below:
* **Health Check Integration**:
* [`src/CommunityToolkit.Aspire.Hosting.Meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.csproj`](diffhunk://#diff-530427004b07ff6537d47fbbdd943b1a6c424fcf837ecfad3838fbe08e4c9104R10): Added `MeilisearchHealthCheck.cs` to the project.
* [`src/CommunityToolkit.Aspire.Hosting.Meilisearch/MeilisearchBuilderExtensions.cs`](diffhunk://#diff-1890e9aa0335fc3968f6157b0026de41bc8fa62f7be6647cb3b05615a97e6cd2L52-R72): Integrated health checks for Meilisearch resources and ensured the …
> Add Waitfor For Meilisearch

- .vscode/settings.json
When the Deno extension is installed it wants to set the default formatter for all files as itself, which will cause all our files to format differently.
Explicitly setting prettier as the formatter by default, but then other languages (like C#) will fall back to their normal default formatter.
> Default Formatter

- .vscode/tasks.json
Add a VSCode task to generate PublicAPI files with a prompt for the project name.
> Initialize PublicAPI file generation task in VSCode

- .devcontainer/devcontainer.json
This will help with local testing against .NET 9, since we use it on CI
> Adding .NET 9 to the devcontainer

- .github/ISSUE_TEMPLATE/bug_report.yml
> Update bug_report issue template replace checkboxes to textarea for nuget-packages

- .github/workflows/dotnet-main.yml
- .github/workflows/dotnet-release.yml
These happen on more specific events so we don't want to do filters
> Removing path filters on main and release CI workflows

- src/CommunityToolkit.Aspire.Hosting.Ollama/GpuVendor.cs
- src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaResourceBuilderExtensions.cs
- src/CommunityToolkit.Aspire.Hosting.Ollama/PublicAPI.Unshipped.txt
- tests/CommunityToolkit.Aspire.Hosting.Ollama.Tests/AddOllamaTests.cs
Added a new method `WithGPUSupport` to the extension methods for when you create an Ollama server resource. Using an enum for the GPU support options.
**Closes #298**
> Ollama GPU support

- src/CommunityToolkit.Aspire.EventStore/CommunityToolkit.Aspire.EventStore.csproj
- src/CommunityToolkit.Aspire.Hosting.ActiveMQ/CommunityToolkit.Aspire.Hosting.ActiveMQ.csproj
- src/CommunityToolkit.Aspire.Hosting.Azure.DataApiBuilder/CommunityToolkit.Aspire.Hosting.Azure.DataApiBuilder.csproj
- src/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps.csproj
- src/CommunityToolkit.Aspire.Hosting.Bun/CommunityToolkit.Aspire.Hosting.Bun.csproj
- src/CommunityToolkit.Aspire.Hosting.Deno/CommunityToolkit.Aspire.Hosting.Deno.csproj
- src/CommunityToolkit.Aspire.Hosting.EventStore/CommunityToolkit.Aspire.Hosting.EventStore.csproj
- src/CommunityToolkit.Aspire.Hosting.Golang/CommunityToolkit.Aspire.Hosting.Golang.csproj
- src/CommunityToolkit.Aspire.Hosting.Java/CommunityToolkit.Aspire.Hosting.Java.csproj
- src/CommunityToolkit.Aspire.Hosting.Meilisearch/CommunityToolkit.Aspire.Hosting.Meilisearch.csproj
- src/CommunityToolkit.Aspire.Hosting.NodeJS.Extensions/CommunityToolkit.Aspire.Hosting.NodeJS.Extensions.csproj
- src/CommunityToolkit.Aspire.Hosting.Ollama/CommunityToolkit.Aspire.Hosting.Ollama.csproj
- src/CommunityToolkit.Aspire.Hosting.Python.Extensions/CommunityToolkit.Aspire.Hosting.Python.Extensions.csproj
- src/CommunityToolkit.Aspire.Hosting.Rust/CommunityToolkit.Aspire.Hosting.Rust.csproj
- src/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects.csproj
- src/CommunityToolkit.Aspire.MassTransit.RabbitMQ/CommunityToolkit.Aspire.MassTransit.RabbitMQ.csproj
- src/CommunityToolkit.Aspire.OllamaSharp/CommunityToolkit.Aspire.OllamaSharp.csproj
- src/Directory.Build.props
It was being added to all projects under src, regardless of whether they are hosting or client integrations. Removed this from the Directory.Build.props and added it to the Hosting integrations only.
Had to update some dependencies across the client integrations as they were getting access to what they needed as transient via Aspire.Hosting
> Changing how Aspire.Hosting is referenced

- .github/workflows/dotnet-ci.yml
With #377 we've identified a problem that means that CI is broken for the Deno integration.
Looking at the build logs it seems that Deno 2.1.5 (released in the past week) is causing failures.
This PR pins the version of 2.1.4 for Deno, which is the last known working version. Admittedly, this is a temporary workaround until we find the underlying problem that comes with Deno 2.1.5
> Deno integration fix

- tests/CommunityToolkit.Aspire.Hosting.ActiveMQ.Tests/AppHostTests.cs
**Contributes to #405**
Just a small part of removing FluentAssertions
> #405 remove FluentAssertions from ActiveMQ test

- src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaContainerImageTags.cs
Use latest openwebui container image
**Closes #429**
Simply updates the OpenWebUI container image to latest to prevent consistent popup of 'new version available'
> Update OpenWebUI container image

- .github/workflows/dotnet-main.yml
- .github/workflows/dotnet-release.yml
This PR adds the `DAPR_VERSION` variable to the `dotnet-main` and the `dotnet-release` actions, which we should have added in #438.
> Fix CI, Followup #438

- Directory.Build.props
- Directory.Packages.props
- examples/ollama/CommunityToolkit.Aspire.Hosting.Ollama.Web/Program.cs
- src/CommunityToolkit.Aspire.OllamaSharp/AspireOllamaApiClientBuilder.cs
- src/CommunityToolkit.Aspire.OllamaSharp/AspireOllamaChatClientExtensions.cs
- src/CommunityToolkit.Aspire.OllamaSharp/AspireOllamaEmbeddingGeneratorExtensions.cs
- src/CommunityToolkit.Aspire.OllamaSharp/AspireOllamaSharpExtensions.cs
- src/CommunityToolkit.Aspire.OllamaSharp/CommunityToolkit.Aspire.OllamaSharp.csproj
- src/CommunityToolkit.Aspire.OllamaSharp/OllamaSharpSettings.cs
- src/CommunityToolkit.Aspire.OllamaSharp/PublicAPI.Unshipped.txt
- tests/CommunityToolkit.Aspire.OllamaSharp.Tests/ConformanceTests.cs
- tests/CommunityToolkit.Aspire.OllamaSharp.Tests/OllamaApiClientTests.cs
- tests/CommunityToolkit.Aspire.OllamaSharp.Tests/OllamaSharpIChatClientTests.cs
- tests/CommunityToolkit.Aspire.OllamaSharp.Tests/OllamaSharpIEmbeddingGeneratorTests.cs
Moving away from our current ways of registering an IChatClient/IEmbeddingGenerator to leverage the builder pattern from MEAI. This allows the consumer to add middleware to the AI pipeline.
Existing methods have been marked as Obsolete.
Set some default middleware with logging and OTEL.
Fixes #461
> Aligning OllamaSharp with the Aspire OpenAI + MEAI design

- Directory.Packages.props
- docs/diagnostics.md
- nuget.config
- src/CommunityToolkit.Aspire.Hosting.Sqlite/CommunityToolkit.Aspire.Hosting.Sqlite.csproj
- src/CommunityToolkit.Aspire.Hosting.Sqlite/PublicAPI.Unshipped.txt
- src/CommunityToolkit.Aspire.Hosting.Sqlite/SqliteResource.cs
- src/CommunityToolkit.Aspire.Hosting.Sqlite/SqliteResourceBuilderExtensions.cs
- src/CommunityToolkit.Aspire.Microsoft.Data.Sqlite/AspireSqliteExtensions.cs
- src/CommunityToolkit.Aspire.Microsoft.Data.Sqlite/CommunityToolkit.Aspire.Microsoft.Data.Sqlite.csproj
- src/CommunityToolkit.Aspire.Microsoft.Data.Sqlite/PublicAPI.Unshipped.txt
- src/CommunityToolkit.Aspire.Microsoft.Data.Sqlite/SqliteConnectionSettings.cs
- src/CommunityToolkit.Aspire.Microsoft.EntityFrameworkCore.Sqlite/AspireEFSqliteExtensions.cs
- src/Shared/Sqlite/SqliteExtensionMetadata.cs
- tests/CommunityToolkit.Aspire.Hosting.Sqlite.Tests/AddSqliteTests.cs
- tests/CommunityToolkit.Aspire.Hosting.Sqlite.Tests/CommunityToolkit.Aspire.Hosting.Sqlite.Tests.csproj
- tests/CommunityToolkit.Aspire.Hosting.Sqlite.Tests/ResourceWithExtensionTests.cs
- tests/CommunityToolkit.Aspire.Microsoft.Data.Sqlite.Tests/ConfigurationTests.cs
- tests/CommunityToolkit.Aspire.Microsoft.Data.Sqlite.Tests/SqliteConnectionTests.cs
- tests/CommunityToolkit.Aspire.Microsoft.EntityFrameworkCore.Sqlite.Tests/SqliteConnectionTests.cs
- tests/CommunityToolkit.Aspire.Testing/RequiresWindowsAttribute.cs
- tests/CommunityToolkit.Aspire.Testing/RequiresWindowsDiscoverer.cs
Adding the ability to specify SQLite extensions that you want to load on the database. Extensions can be shipped as NuGet packages (https://www.nuget.org/packages/mod_spatialite is an example) or you can specify a path to the extension binary (an absolute path).
This is done in the app host and the info is projected as part of the connection string for the client.
In the client library, it'll read the extensions from the connection string (then delete that value so it is a valid connection string) and load the extensions using the SqliteConnection. Since SQLite needs the extension to be in PATH ([see this doc](https://learn.microsoft.com/dotnet/standard/data/sqlite/extensions)) there is a bit of code to ensure the path for the binary is loaded correctly.
I've added some tests for …
> Adding ability to configure extensions for Sqlite

- src/CommunityToolkit.Aspire.Hosting.Python.Extensions/PublicAPI.Shipped.txt
- src/CommunityToolkit.Aspire.Hosting.Python.Extensions/PublicAPI.Unshipped.txt
- src/CommunityToolkit.Aspire.Hosting.Python.Extensions/UvAppHostingExtension.cs
- src/CommunityToolkit.Aspire.Hosting.Python.Extensions/UvAppResource.cs
- src/CommunityToolkit.Aspire.Hosting.Python.Extensions/UvicornAppHostingExtension.cs
- src/CommunityToolkit.Aspire.Hosting.Python.Extensions/UvicornAppResource.cs
> OTEL for python extensions

- src/CommunityToolkit.Aspire.OllamaSharp/AspireOllamaChatClientExtensions.cs
- src/CommunityToolkit.Aspire.OllamaSharp/AspireOllamaEmbeddingGeneratorExtensions.cs
- tests/CommunityToolkit.Aspire.OllamaSharp.Tests/OllamaSharpIChatClientTests.cs
- tests/CommunityToolkit.Aspire.OllamaSharp.Tests/OllamaSharpIEmbeddingGeneratorTests.cs
1. Enable logging in the OpenTelemetry clients
2. Ensure the OpenTelemetry clients are immediately wrapped around the raw api client. This ensures all calls to the Ollama api are logged correctly.
**Closes #508**
> Fix Ollama OpenTelemetry pipeline

- examples/mailpit/CommunityToolkit.Aspire.Hosting.MailPit.AppHost/Program.cs
- src/CommunityToolkit.Aspire.Hosting.MailPit/MailPitHostingExtension.cs
- tests/CommunityToolkit.Aspire.Hosting.MailPit.Tests/AppHostHealthChecksTests.cs
**Closes #511**
Replace health-checks added via `/` route, to health checks exposed by MailPit at `/livez` and `/readyz` routes.
> Fix Mailpit health check status

- src/CommunityToolkit.Aspire.Hosting.NodeJS.Extensions/NodeJSHostingExtensions.cs
- src/CommunityToolkit.Aspire.Hosting.NodeJS.Extensions/PublicAPI.Unshipped.txt
- tests/CommunityToolkit.Aspire.Hosting.NodeJS.Extensions.Tests/ResourceCreationTests.cs
**Closes #518**
Just add an useHttps optional parameter to the AddViteApp method.
- [x ] Created a feature/dev branch in your fork (vs. submitting directly from a commit on main)
entire description over that)
This PR contains a breaking change as it adds an optional parameter to an existing method.
> Add optional parameter to use https for ViteApp

- Directory.Packages.props
- src/CommunityToolkit.Aspire.OllamaSharp/AspireOllamaSharpExtensions.cs
- src/CommunityToolkit.Aspire.OllamaSharp/CommunityToolkit.Aspire.OllamaSharp.csproj
This means that we can leverage the configurations applied to HttpClient via ServiceDefault around stuff like resiliancy, rather than creating a HttpClient in isolation that is not aware of any of that configuration.
No new tests are added as there's not we could easily test with this, but all existing tests should continue to pass
Fixes #474
> Using the built-in method to register a HttpClient in .NET for OllamaSharp

- src/CommunityToolkit.Aspire.Hosting.Python.Extensions/UvicornAppHostingExtension.cs
When adding a Python resource using `AddUvicornApp` and using `uvicorn`, use `uvicorn` from the virtual environment if available, before choosing `uvicorn` from the current active python env.
This is particularly important when running multiple python resources, each with a potentially different version of uvicorn, each stored in separate environments under the resource.
Closes #545
This might be considered a breaking change for local development when running python resources off the host python env, without activating the resource venv. Worth evaluating, but the previous implementation seems to depend on some lucky factors, like python resources aligned on the same version and the venv being activated before launching Aspire AppHost.
> Use “uvicorn” from .venv if available

- src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaResourceBuilderExtensions.cs
We don't need it, since we have no OTEL stuff in the Ollama container, and having it triggers https://github.com/dotnet/aspire/issues/6889
Fixing #559
> Removing .WithOtlpExporter from Ollama container setup

- src/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects/SqlProjectBuilderExtensions.cs
- src/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects/SqlProjectResource.cs
**Closes #590**
This change takes the assembly calling the `AddSqlProject` extension method for determining the build configuration. The `AddSqlProject` extension method is usually called from the AppHost project and is used to more reliably determine the build configuration. This works for both during running the AppHost as well as during integration testing.
This is my first contribution to this project. Please let me know things I should improve!
> Use calling assembly for determining build configuration

- .github/actions/setup-runtimes-caching/action.yml
- .github/workflows/dotnet-ci.yml
- .github/workflows/dotnet-main.yml
- .github/workflows/dotnet-release.yml
- .github/workflows/tests.yaml
- tests/CommunityToolkit.Aspire.Testing/AspireIntegrationTest.cs
- **Allowing the override of the container registry for CI**
- **Updating workflows to set the custom registry**
> custom registry for ci

- src/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects/SqlProjectBuilderExtensions.cs
**Closes #502**
This ensures that `SqlProject` and `SqlPackage` resources are nested underneath the `SqlServerDatabase` resource in the Aspire dashboard, like this:
- [-] New integration
- [-] Docs are written
- [-] Added description of major feature to project description for NuGet package (4000 total character limit, so don't push entire description over that)
> Use WithParentRelationship to nest resources

- .github/workflows/tests.yaml
- CommunityToolkit.Aspire.sln
- examples/adminer/CommunityToolkit.Aspire.Hosting.Adminer.AppHost/CommunityToolkit.Aspire.Hosting.Adminer.AppHost.csproj
- examples/adminer/CommunityToolkit.Aspire.Hosting.Adminer.AppHost/Program.cs
- examples/adminer/CommunityToolkit.Aspire.Hosting.Adminer.AppHost/Properties/launchSettings.json
- examples/adminer/CommunityToolkit.Aspire.Hosting.Adminer.AppHost/appsettings.json
- examples/postgres-ext/CommunityToolkit.Aspire.Hosting.PostgreSQL.Extensions.AppHost/Program.cs
- src/CommunityToolkit.Aspire.Hosting.Adminer/AdminerBuilderExtensions.cs
- src/CommunityToolkit.Aspire.Hosting.Adminer/AdminerContainerImageTags.cs
- src/CommunityToolkit.Aspire.Hosting.Adminer/AdminerContainerResource.cs
- src/CommunityToolkit.Aspire.Hosting.Adminer/AdminerLoginServer.cs
- src/CommunityToolkit.Aspire.Hosting.Adminer/CommunityToolkit.Aspire.Hosting.Adminer.csproj
- src/CommunityToolkit.Aspire.Hosting.Adminer/README.md
- src/CommunityToolkit.Aspire.Hosting.Adminer/login-servers.php
- src/CommunityToolkit.Aspire.Hosting.PostgreSQL.Extensions/CommunityToolkit.Aspire.Hosting.PostgreSQL.Extensions.csproj
- src/CommunityToolkit.Aspire.Hosting.PostgreSQL.Extensions/PostgresBuilderExtensions.cs
- src/CommunityToolkit.Aspire.Hosting.PostgreSQL.Extensions/README.md
- src/Shared/Adminer/AdminerLoginServer.cs
- tests/CommunityToolkit.Aspire.Hosting.Adminer.Tests/AddAdminerTests.cs
- tests/CommunityToolkit.Aspire.Hosting.Adminer.Tests/AdminerPublicApiTests.cs
- tests/CommunityToolkit.Aspire.Hosting.Adminer.Tests/AppHostTests.cs
- tests/CommunityToolkit.Aspire.Hosting.Adminer.Tests/CommunityToolkit.Aspire.Hosting.Adminer.Tests.csproj
- tests/CommunityToolkit.Aspire.Hosting.PostgreSQL.Extensions.Tests/CommunityToolkit.Aspire.Hosting.PostgreSQL.Extensions.Tests.csproj
- tests/CommunityToolkit.Aspire.Hosting.PostgreSQL.Extensions.Tests/ResourceCreationTests.cs
**Closes #436**
**Only Postgres is supported at this PR.**
https://github.com/user-attachments/assets/685cc772-ed88-45c4-9bb9-dfc7cb282e9a
This pull request introduces a new feature for integrating Adminer with the CommunityToolkit.Aspire project. The changes include adding new projects, updating existing projects, and modifying configuration files to support the Adminer integration.
New Projects and Integration:
* Added `CommunityToolkit.Aspire.Hosting.Adminer` project to the solution, including its configuration and dependencies. [[1]](diffhunk://#diff-535a41475832da4913135fd47e0c392a6b5a874479086cdd597326b24bffd248R376-R383) [[2]](diffhunk://#diff-d8a4aca642f84e56b6ec3c9a3c64e8ca72b4603e0c8c4cf2a13c7778eb9b2106R1-R19)
* Created a new example project …
> Add adminer integration

- Directory.Packages.props
- src/CommunityToolkit.Aspire.Hosting.MongoDB.Extensions/MongoDBBuilderExtensions.cs
- src/CommunityToolkit.Aspire.Hosting.PostgreSQL.Extensions/PostgresBuilderExtensions.cs
- src/CommunityToolkit.Aspire.Hosting.Redis.Extensions/RedisBuilderExtensions.cs
- src/CommunityToolkit.Aspire.Hosting.SqlServer.Extensions/CommunityToolkit.Aspire.Hosting.SqlServer.Extensions.csproj
- src/CommunityToolkit.Aspire.Hosting.SqlServer.Extensions/SqlServerBuilderExtensions.cs
Let users explicitly use `WaitFor`.
> Remove implicit `WaitFor` in `WithDbGate`

- .github/workflows/dotnet-ci.yml
- tests-app-hosts/Directory.Build.props
This pull request removes an unused property group from the `tests-app-hosts/Directory.Build.props` file to clean up the project configuration.
There is no need for this property because we removed this analyzer earlier.
> Removed UsePublicApiAnalyzers property

- src/CommunityToolkit.Aspire.Hosting.Adminer/AdminerBuilderExtensions.cs
- src/CommunityToolkit.Aspire.Hosting.DbGate/DbGateBuilderExtensions.cs
- tests/CommunityToolkit.Aspire.Hosting.Adminer.Tests/AddAdminerTests.cs
- tests/CommunityToolkit.Aspire.Hosting.DbGate.Tests/AddDbGateTests.cs
> Add display name for DbGate and Adminer

- .github/dependabot.yml
Dependbot usually updates these in the wrong way.
For example, see:
https://github.com/CommunityToolkit/Aspire/pull/651/files#diff-9da24614831c308827a1ae533ffea392c97638c261dd42bd0f5226baa136d16eR14
On the other hand, we manually update the Aspire version.
> Ignore dependency updating check for Aspire.Hosting and Aspire.Hosting.*

- .github/workflows/generate-api-diffs.yml
> Do not run `Generate API Diffs` workflow on forks

- src/CommunityToolkit.Aspire.Hosting.Adminer/AdminerBuilderExtensions.cs
> Use `WithContainerFiles` in adminer integeration

- tests/CommunityToolkit.Aspire.Hosting.EventStore.Tests/EventStoreFunctionalTests.cs
https://github.com/dotnet/aspire/issues/4878 has been resolved, so there is no need for this delay.
Fixes #301
> Remove Task.Delay from EventStore tests

- examples/sql-database-projects/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects.AppHost/Program.cs
- src/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects/SqlProjectBuilderExtensions.cs
- tests/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects.Tests/AddSqlProjectTests.cs
**Closes #638**
Add explicit start option for SQL projects
Update to check for `ExplicitStartupAnnotation` to determine resource state. Modify the redeploy command and add a test case in `AddSqlProjectTests.cs` to verify the new behavior.
> fixes #638

- examples/adminer/CommunityToolkit.Aspire.Hosting.Adminer.AppHost/CommunityToolkit.Aspire.Hosting.Adminer.AppHost.csproj
- examples/adminer/CommunityToolkit.Aspire.Hosting.Adminer.AppHost/Program.cs
- examples/sqlserver-ext/CommunityToolkit.Aspire.Hosting.SqlServer.Extensions.AppHost/Program.cs
- src/CommunityToolkit.Aspire.Hosting.SqlServer.Extensions/CommunityToolkit.Aspire.Hosting.SqlServer.Extensions.csproj
- src/CommunityToolkit.Aspire.Hosting.SqlServer.Extensions/README.md
- src/CommunityToolkit.Aspire.Hosting.SqlServer.Extensions/SqlServerBuilderExtensions.cs
- tests/CommunityToolkit.Aspire.Hosting.Adminer.Tests/AddAdminerTests.cs
- tests/CommunityToolkit.Aspire.Hosting.SqlServer.Extensions.Tests/CommunityToolkit.Aspire.Hosting.SqlServer.Extensions.Tests.csproj
- tests/CommunityToolkit.Aspire.Hosting.SqlServer.Extensions.Tests/ResourceCreationTests.cs
Contributes to #643 
This pull request introduces support for integrating Adminer with SQL Server resources in the `CommunityToolkit.Aspire.Hosting.SqlServer.Extensions` package. The changes include adding a new `WithAdminer` method, updating documentation, and implementing comprehensive tests to validate the functionality.
* Added a `WithAdminer` extension method to `SqlServerBuilderExtensions` to enable Adminer as an administration and development platform for SQL Server resources. This includes configuring Adminer containers and managing environment variables for SQL Server instances. [[1]](diffhunk://#diff-95cf3bf5cd992d5b22fc344d8a08f32171c12d4770348dd8c34be781a545ecebR53-R92) [[2]](diffhunk://#diff-95cf3bf5cd992d5b22fc344d8a08f32171c12d4770348dd8c34be781a545ecebR137-R177)
* Updated …
> Add Adminer support for SqlServer

- .github/actions/setup-runtimes-caching/action.yml
- docs/diagnostics.md
- examples/swa/CommunityToolkit.Aspire.StaticWebApps.AppHost/CommunityToolkit.Aspire.StaticWebApps.AppHost.csproj
- examples/swa/CommunityToolkit.Aspire.StaticWebApps.AppHost/Program.cs
- src/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps/README.md
- src/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps/SwaApiEndpointAnnotation.cs
- src/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps/SwaAppEndpointAnnotation.cs
- src/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps/SwaAppHostingExtension.cs
- src/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps/SwaResource.cs
- src/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps/SwaResourceOptions.cs
- tests/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps.Tests/ResourceCreationTests.cs
- tests/CommunityToolkit.Aspire.Hosting.Azure.StaticWebApps.Tests/SwaHostingComponentTests.cs
Update project references and improve app setup
- Added project reference for `CommunityToolkit.Aspire.Hosting.NodeJS.Extensions.csproj` in `CommunityToolkit.Aspire.StaticWebApps.AppHost.csproj`.
- Changed web app setup in `Program.cs` from `.AddNpmApp` to `.AddViteApp` with `.WithNpmPackageInstallation()`.
- Modified `Port` property in `SwaResourceOptions.cs` to use a random port between 4280 and 5280.
- Updated tests in `SwaHostingComponentTests.cs` to utilize `CancellationToken` for better control over async operations.
Related Work Items: #698, #677
> SWA test stability

- src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaContainerImageTags.cs
- src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaResourceBuilderExtensions.cs
- tests/CommunityToolkit.Aspire.Hosting.Ollama.Tests/AddOllamaTests.cs
- **SWA test stability (#697)**
- **Add DbGate support for MySql (#695)**
- **Update container image tags and GPU support methods**
> Fixing AMD GPU support for Ollama

- src/CommunityToolkit.Aspire.Hosting.Golang/GolangAppHostingExtension.cs
- tests/CommunityToolkit.Aspire.Hosting.Golang.Tests/ResourceCreationTests.cs
**Closes #730**
I updated `GolangAppHostingExtension` to support specifying Go build tags to be used when building and running Go applications. Go build tags can be used to include or exclude files from the build process based On specific conditions. For example, when using Aspire for development, a Go developer may use a build tag to enable special code for OpenTelemetry instrumentation or enable debugging features.
I created a unit test to verify that the build tag was being passed in the command line to the `go` command.
I accomplished my change by adding a new argument to the `GolangAppHostingExtension.AddGolangApp` method, but the new argument is marked as optional and has a default null value. This should not break existing consumers of the `AddGolandApp` method or make them alter …
> Add Go Build Tags Support

- examples/sql-database-projects/SdkProject/Database.publish.xml
- src/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects/DacDeployOptionsAnnotation.cs
- src/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects/SqlPackageResource.cs
- src/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects/SqlProjectBuilderExtensions.cs
- src/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects/SqlProjectResource.cs
- tests/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects.Tests/AddSqlPackageTests.cs
- tests/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects.Tests/AddSqlProjectTests.cs
- tests/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects.Tests/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects.Tests.csproj
- tests/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects.Tests/Database.publish.xml
fixes #694
**Closes #694**
Adds a ne WithDacDeployOptions method that takes a path to a publish xml profile
> Add support for DacDeployOption from a publish profile

- src/CommunityToolkit.Aspire.Hosting.NodeJS.Extensions/NodeJSHostingExtensions.cs
- tests/CommunityToolkit.Aspire.Hosting.NodeJS.Extensions.Tests/PackageInstallationTests.cs
Changed to using a callback rather than an array of args.
Fixes #738
> Node installer tweaks

- src/CommunityToolkit.Aspire.Hosting.NodeJS.Extensions/NodeJSHostingExtensions.cs
**Closes #760**
Run `configureInstaller` after `WaitForCompletion` in the `WithXYZPackageInstallation` methods
> Run `configureInstaller` after `WaitForCompletion` in `WithXYZPackageInstallation` methods

- src/CommunityToolkit.Aspire.Hosting.McpInspector/McpInspectorResourceBuilderExtensions.cs
- src/CommunityToolkit.Aspire.Hosting.McpInspector/McpTransportType.cs
- tests/CommunityToolkit.Aspire.Hosting.McpInspector.Tests/McpInspectorResourceBuilderExtensionsTests.cs
> Marking SSE transport as deprecated

- src/CommunityToolkit.Aspire.Hosting.McpInspector/McpInspectorResource.cs
- src/CommunityToolkit.Aspire.Hosting.McpInspector/McpInspectorResourceBuilderExtensions.cs
**Closes #776**
- 🔧 Bump InspectorVersion from 0.15.0 to 0.16.2
- 📦 Add inspectorVersion parameter to AddMcpInspector method allowing for overriding of Inspector version to use, while retaining default for package if not provided
> Update MCP Inspector version and extension method parameters

- src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaContainerImageTags.cs
**Note** - This uses a version of Ollama that is not released yet, but is likely to release shortly so the PR is pre-emptive
> Ollama 0.11

- docs/diagnostics.md
- examples/surrealdb/CommunityToolkit.Aspire.Hosting.SurrealDb.AppHost/Program.cs
- src/CommunityToolkit.Aspire.Hosting.SurrealDb/CommunityToolkit.Aspire.Hosting.SurrealDb.csproj
- src/CommunityToolkit.Aspire.Hosting.SurrealDb/SurrealDbBuilderExtensions.cs
- src/CommunityToolkit.Aspire.SurrealDb/SurrealDbHealthCheck.cs
- src/CommunityToolkit.Aspire.SurrealDb/SurrealDbNamespaceHealthCheck.cs
- tests/CommunityToolkit.Aspire.Hosting.SurrealDb.Tests/SurrealDbFunctionalTests.cs
- tests/CommunityToolkit.Aspire.Hosting.SurrealDb.Tests/SurrealDbPublicApiTests.cs
> Unblocking CI with SurrealDB tests

- examples/mcp-inspector/CommunityToolkit.Aspire.Hosting.McpInspector.McpServer/Program.cs
- src/CommunityToolkit.Aspire.Hosting.McpInspector/McpInspectorResource.cs
- src/CommunityToolkit.Aspire.Hosting.McpInspector/McpInspectorResourceBuilderExtensions.cs
- src/CommunityToolkit.Aspire.Hosting.McpInspector/McpServerMetadata.cs
- tests/CommunityToolkit.Aspire.Hosting.McpInspector.Tests/McpInspectorResourceBuilderExtensionsTests.cs
Enable immediate inspection of the MCP inspector by loading the config file. Update the MCP server path handling to allow custom paths for communication.
> Load config file for MCP inspector and update path handling

- src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaContainerImageTags.cs
Update the version tags for the Ollama and Open WebUI images to the latest releases.
> Bump Ollama and Open WebUI tags

- src/CommunityToolkit.Aspire.Hosting.McpInspector/McpInspectorResourceBuilderExtensions.cs
- tests/CommunityToolkit.Aspire.Hosting.McpInspector.Tests/McpInspectorResourceBuilderExtensionsTests.cs
> Adding more test coverage and fixing URL handling

- src/CommunityToolkit.Aspire.Hosting.McpInspector/McpInspectorResourceBuilderExtensions.cs
- tests/CommunityToolkit.Aspire.Hosting.McpInspector.Tests/McpInspectorResourceBuilderExtensionsTests.cs
> Adding some more descriptive relationships to the MCP inspector

- src/CommunityToolkit.Aspire.Hosting.Bun/README.md
- src/CommunityToolkit.Aspire.Hosting.Deno/README.md
- src/CommunityToolkit.Aspire.Hosting.PostgreSQL.Extensions/README.md
- src/CommunityToolkit.Aspire.RavenDB.Client/README.md
> Fix several broken links in package readmes

- src/CommunityToolkit.Aspire.Hosting.OpenTelemetryCollector/OpenTelemetryCollectorExtensions.cs
- tests/CommunityToolkit.Aspire.Hosting.OpenTelemetryCollector.Tests/ResourceCreationTests.cs
**Closes #857**
The `IsDevelopment` environment check when adding dev certs is a bit excessive - there is already a `IsRunMode` guard to protect against injecting dev certs in published environments.
limit, so don't push entire description over that)
> Remove `Development` environments check from otel collector

- src/CommunityToolkit.Aspire.Hosting.OpenTelemetryCollector/OpenTelemetryCollectorExtensions.cs
- src/Shared/DevCertHostingExtensions.cs
Make use of the `WithIconName` API added in 9.5:
After:
Before:
> [9.5]: Add icons to the otel collector & dev cert export

- src/CommunityToolkit.Aspire.Hosting.OpenTelemetryCollector/README.md
Added some missing text to the first example.
> Update Otel Collector Readme
